# Configuracion del modelo Python
model:
  service:
    url: ${MODEL_SERVICE_URL:http://localhost:8000}
    timeout: 5000

# Logging
logging:
  level:
    root: INFO
    com.one.hackathonlatam.dic25equipo69.churninsight: DEBUG
  file:
    name: logs/churn-insight-dev.log
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"